name: manual-workflow

on: workflow_dispatch

jobs:

 first-workflow-jobs:
   runs-on: ubuntu-latest

   steps:
    - name: first-steps
      run: |
       echo "hello world"
       echo "hello again"